import React from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-950 via-gray-900 to-gray-950 text-white">
      <div className="container mx-auto px-4 py-16">
        <h1 className="text-4xl font-bold mb-8 text-center">
          Terms of Service
        </h1>

        <div className="space-y-8 max-w-3xl mx-auto text-gray-300">
          <section>
            <h2 className="text-2xl font-semibold text-white mb-2">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using DocuMentor, you agree to be bound by these
              Terms of Service. If you do not agree, please do not use our
              platform.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-2">
              2. Description of Service
            </h2>
            <p>
              DocuMentor provides AI-powered tools to summarize documents and
              generate quizzes. These services are intended for personal,
              academic, and educational use only.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-2">
              3. User Responsibilities
            </h2>
            <ul className="list-disc list-inside ml-4 mt-2">
              <li>
                You are responsible for all content you upload and generate
                using our platform.
              </li>
              <li>
                Do not upload content that is illegal, harmful, or violates
                intellectual property rights.
              </li>
              <li>Use DocuMentor ethically and within legal limits.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-2">
              4. Account & Security
            </h2>
            <p>
              If you create an account, you are responsible for maintaining the
              confidentiality of your credentials. DocuMentor is not liable for
              any loss or damage resulting from unauthorized access to your
              account.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-2">
              5. Intellectual Property
            </h2>
            <p>
              All content generated by DocuMentor’s AI is provided for your use
              but remains the intellectual property of DocuMentor. You may not
              resell or distribute generated content commercially without
              permission.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-2">
              6. Limitation of Liability
            </h2>
            <p>
              DocuMentor is provided “as-is.” We do our best to ensure accuracy,
              but we do not guarantee the completeness or correctness of
              generated content. Use the platform at your own discretion.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-2">
              7. Termination
            </h2>
            <p>
              We reserve the right to suspend or terminate your access if you
              violate these Terms or misuse the service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-2">
              8. Changes to Terms
            </h2>
            <p>
              These Terms may be updated occasionally. Continued use of
              DocuMentor after changes means you accept the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-2">
              9. Contact
            </h2>
            <p>
              For questions or concerns about these Terms, please email us at{" "}
              <a
                href="mailto:support@documentor.ai"
                className="text-cyan-400 underline"
              >
                support@documentor.ai
              </a>
              .
            </p>
          </section>
        </div>
      </div>
      <Footer />
    </div>
  );
}
